# SITE CONFIGURATION
title: AIm High # your site title
author: mzwesley # You :P
description: > # Meta description of Homepage
  Work with AI
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mzwesley.github.io/AIm-High" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: mzwesley
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/mzwesley
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: ''}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  涵蓋各領域、直擊問題點、精簡好閱聽 的資訊平臺，將訪問影片與訪問文章的精華片段發布於上，期待青年學子們能藉著此網站，獲知在自己的專業內，來自就業市場需求者的第一手資訊。

hero_img: background.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: mzwesley@gmail.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  mzwesley # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: mzwesley # to enable comments replace with your_disqus_shortname

# GOOGLE SERVICES
# google_tag_manager: GTM-MCMHCRS  # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_analytics: UA-164373961-1

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
